### ISSUE TITLE
[Bug] 1.8.6? & Shit in Notification

### ISSUE THREAD

**Issue by MadTooth** [mywalkb/LSPosed_mod#10]
### Steps to reproduce/复现步骤

Check installed version
&
Can you add a setting of a notice to LSPOSED?
![Screenshot_20230202-001610_Magisk](https://user-images.githubusercontent.com/30464341/216116818-0bb6d370-106a-4fdf-b57d-06a928c24047.png)
![Screenshot_20230202-001855_Trebuchet](https://user-images.githubusercontent.com/30464341/216116894-1bb7d98b-0e0f-4534-89ac-8569d27db7ba.png)
![Screenshot_20230202-001909_Trebuchet](https://user-images.githubusercontent.com/30464341/216116965-5ae8b39f-7579-4275-a726-552d8c16168d.png)

### Expected behaviour/预期行为

-

### Actual behaviour/实际行为

-

### Xposed Module List/Xposed 模块列表

```shell
-
```

### Magisk Module List/Magisk 模块列表

```shell
-
```

### LSPosed version/LSPosed 版本

-

### Android version/Android 版本

-

### Magisk version/Magisk 版本

-

### Riru version/Riru 版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

-

**Comment by mywalkb** [comment]
I forgot to a git tag while the release so the version is 1.8.6 but is marked as 1.8.5.
For notification you should this setting 

![Screenshot_2023-02-02-18-36-29-179-edit_org lsposed manager](https://user-images.githubusercontent.com/66966897/216400183-ba7d1666-6a06-438b-832b-6c9eb5566ab8.jpg)

for disable notification. It's one of original changes in 1.8.6. It's not my setting.

**Comment by MadTooth** [comment]
Fixed
![Screenshot_20230203-174156_Shell](https://user-images.githubusercontent.com/30464341/216581234-7bc13e54-95be-42e8-8381-2cd5eee77db7.png)
![Screenshot_20230203-174005_Trebuchet](https://user-images.githubusercontent.com/30464341/216581279-3ec1aeaa-bae3-49f8-b65c-bfb68f3d9a43.png)
![Screenshot_20230203-174337_Shell](https://user-images.githubusercontent.com/30464341/216581413-d23c7a76-f5b3-46a2-a4aa-5dab9dfb0d9a.png)
