### ISSUE TITLE
[Bug] VERY (!!!) small issue

### ISSUE THREAD

**Issue by TheHippoMan** [mywalkb/LSPosed_mod#13]
### Steps to reproduce/复现步骤

1. Open up Magisk
2. Look at the list of installed modules.
3. Examine the version number of the installed LSPosed_mod module. It's listed as follows: _**v1.8.5_mod (6821)**_

### Expected behaviour/预期行为

The download file for LSPosed_mod has this name:
_**LSPosed-v1.8.6_mod-6821-riru-release.zip**_

Therefore, when examining the installed LSPosed_mod module in Magisk, 
the version number should say ...

**_v1.8.6_mod (6821)_**

### Actual behaviour/实际行为

The download file for LSPosed_mod has this name:
_**LSPosed-v1.8.6_mod-6821-riru-release.zip**_

However, when installed in Magisk, the module is actually listed with this incorrect name:
_**v1.8.5_mod (6821)**_

One says "1.8.6", and the other says "1.8.5".

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
None, except LSPosed_mod
```

### LSPosed version/LSPosed 版本

6821

### Android version/Android 版本

Android 11

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

v26.1.7.r530.ab3086ec9f

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2023-03-26T16_14_25Z.log](https://github.com/mywalkb/LSPosed_mod/files/11072918/magisk_log_2023-03-26T16_14_25Z.log)

**Comment by mywalkb** [comment]
I forgot to add a git tag while the release so the version is 1.8.6 but is marked as 1.8.5.
If you want see 1.8.6 you can install latest action, it's stable and there are only smsll changes.
