### ISSUE TITLE
[Feature Request]  update pls

### ISSUE THREAD

**Issue by jksalva42** [mywalkb/LSPosed_mod#15]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I appreciate your hard work... But i need update for this module. Its an amazing function is automatic app select. Pls update your module for future. Thnx

### Describe the solution you'd like/描述你想要的解决方案

Need update

### Additional context/其他信息

Update

**Comment by mywalkb** [comment]
Could you explain better you request?
Which update do you need? 
I'm keeping in sync with main repository ASAP.

**Comment by jksalva42** [comment]
Dex optimization support failed... Pls bro update with main repository. Thnx

**Comment by mywalkb** [comment]
Is already update with latest main repository. 
I'm keeping in sync.
Have you tried LSPosed without mod?
Which version of android have you?
Dex optimization is supported from Android 10+.

**Comment by jksalva42** [comment]
Bro i am using Android 11 and 13

**Comment by mywalkb** [comment]
Try to install original LSPosed and verify if you have the same issue, in my mod dex2oat is not modified, so is better open an issue in original repository with debug logs.
