### ISSUE TITLE
[Feature Request] Select all and automatic add new application

### ISSUE THREAD

**Issue by mywalkb** [mywalkb/LSPosed_mod#2]
Many users ask for these feature requests in original LSPosed but developers always reply with wont fix.

@MadTooth @noahfriedman @just-Nob @araafroyall @279358738 @ardugitter @v-dawg @DanSman @cumhuronat @prvdn @password123123123 @runapp @xKippi @crazed-translator @itachiccc @gabrc52 @green1052 @Evengard @runalsh @NULL0B 
in [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/2561655906) actions there is the packages which implements the feature select all + select none and the feature "automatic add" when it is enabled for a module, each new app installed is automatically added to scope of module.

I searched in all issues for all users which ask these feature, I hope I have not forgotten anyone.

**Comment by green1052** [comment]
👍

**Comment by mywalkb** [comment]
Thanks everyone for the positive feedback

**Comment by mywalkb** [comment]
This feature is now included in last stable release 1.8.5.

**Comment by just-Nob** [comment]
> This feature is now included in last stable release 1.8.5.
> 

Thanks a lot for this result!
Anyway, maybe I'm outing me being a little silly or blind, but where to find these settings?
I expected them here:
![Screenshot_20221115-111653.png](https://user-images.githubusercontent.com/25401767/202369748-741221d1-3aad-4341-bd98-b179b73b5a81.png)
I have version 1.8.5 (6649) installed.

**Comment by Evengard** [comment]
![Screenshot_2022-11-17-13-27-54-08_084ab3bc34f7aa7ccff83653f52abafc](https://user-images.githubusercontent.com/798735/202423649-dd726b78-2fb1-4833-b40b-c3d0112f8403.jpg)

looks like that for me, did you install the official version instead of the fork?

**Comment by just-Nob** [comment]
Indeed, I updated via Fox's Magisk Module Manager, if I remember right.

**Comment by just-Nob** [comment]
I'll try to get 1.8.5 (6749) from Github.

**Comment by mywalkb** [comment]
> I'll try to get 1.8.5 (6749) from Github.

you can try [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/3447716026) action, it's the first commit after stable release, so the next time, will be ok.

**Comment by araafroyall** [comment]
Thanks.
