### ISSUE TITLE
[Feature Request] Notification When New Module Uploaded 

### ISSUE THREAD

**Issue by fgjaee** [mywalkb/LSPosed_mod#21]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No. 

### Describe the solution you'd like/描述你想要的解决方案

When a new module is uploaded a notification would be nice to be able to check out the new module. 

### Additional context/其他信息

Maybe a on/off switch for this notification as well.

**Comment by mywalkb** [comment]
Do you want a background notification?
When the app starts it already notifies you of the availability of an update.

**Comment by fgjaee** [comment]
I get an update if there's an update for my installed modules. I like to check out new modules but never know when there are new uploads. This is what I'd like a notification for.

**Comment by mywalkb** [comment]
I think it will be very hard todo, in [this](https://github.com/LSPosed/LSPosed/issues/2815) issue is marked as not possible.

**Comment by araafroyall** [comment]
> I get an update if there's an update for my installed modules. I like to check out new modules but never know when there are new uploads. This is what I'd like a notification for. 

You can use github for these notifications 👍

**Comment by mywalkb** [comment]
I tried many way solution without success, so for now I close as not planned.
