### ISSUE TITLE
No lsposed module path found

### ISSUE THREAD

**Issue by u2shana** [mywalkb/LSPosed_mod#23]
### Steps to reproduce/复现步骤

![Screenshot_2023-11-01-14-36-36-282_bin mt plus](https://github.com/mywalkb/LSPosed_mod/assets/14146754/c4a4aa54-fe02-4d00-bd55-1d270237c605)
Can't use cli

### Expected behaviour/预期行为

none

### Actual behaviour/实际行为

none

### Xposed Module List/Xposed 模块列表

```shell
none
```

### Magisk Module List/Magisk 模块列表

```shell
none
```

### LSPosed version/LSPosed 版本

7183

### Android version/Android 版本

13

### Magisk version/Magisk 版本

aphla26302

### Riru version/Riru 版本

none

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

none

**Comment by mywalkb** [comment]
Could you post the output of command:

```
find $(magisk --path)
```

**Comment by u2shana** [comment]
> Could you post the output of command:
> 
> ```
> find $(magisk --path)
> ```

/debug_ramdisk
/debug_ramdisk/shamiko
/debug_ramdisk/shamiko/status
/debug_ramdisk/shamiko/module.prop
/debug_ramdisk/magiskpolicy
/debug_ramdisk/magisk
/debug_ramdisk/magisk64
/debug_ramdisk/magisk32
/debug_ramdisk/supolicy
/debug_ramdisk/resetprop
/debug_ramdisk/su
/debug_ramdisk/.magisk
/debug_ramdisk/.magisk/busybox
/debug_ramdisk/.magisk/busybox/zcip
/debug_ramdisk/.magisk/busybox/zcat
/debug_ramdisk/.magisk/busybox/yes
/debug_ramdisk/.magisk/busybox/xzcat
/debug_ramdisk/.magisk/busybox/xz
/debug_ramdisk/.magisk/busybox/xxd
/debug_ramdisk/.magisk/busybox/xargs
/debug_ramdisk/.magisk/busybox/whois
/debug_ramdisk/.magisk/busybox/whoami
/debug_ramdisk/.magisk/busybox/which
/debug_ramdisk/.magisk/busybox/wget
/debug_ramdisk/.magisk/busybox/wc
/debug_ramdisk/.magisk/busybox/watchdog
/debug_ramdisk/.magisk/busybox/watch
/debug_ramdisk/.magisk/busybox/volname
/debug_ramdisk/.magisk/busybox/vi
/debug_ramdisk/.magisk/busybox/vconfig
/debug_ramdisk/.magisk/busybox/uuencode
/debug_ramdisk/.magisk/busybox/uudecode
/debug_ramdisk/.magisk/busybox/usleep
/debug_ramdisk/.magisk/busybox/uptime
/debug_ramdisk/.magisk/busybox/unzip
/debug_ramdisk/.magisk/busybox/unxz
/debug_ramdisk/.magisk/busybox/unshare
/debug_ramdisk/.magisk/busybox/unlzop
/debug_ramdisk/.magisk/busybox/unlzma
/debug_ramdisk/.magisk/busybox/unlink
/debug_ramdisk/.magisk/busybox/unix2dos
/debug_ramdisk/.magisk/busybox/uniq
/debug_ramdisk/.magisk/busybox/unexpand
/debug_ramdisk/.magisk/busybox/uncompress
/debug_ramdisk/.magisk/busybox/uname
/debug_ramdisk/.magisk/busybox/umount
/debug_ramdisk/.magisk/busybox/uevent
/debug_ramdisk/.magisk/busybox/udpsvd
/debug_ramdisk/.magisk/busybox/udhcpd
/debug_ramdisk/.magisk/busybox/udhcpc6
/debug_ramdisk/.magisk/busybox/udhcpc
/debug_ramdisk/.magisk/busybox/ubiupdatevol
/debug_ramdisk/.magisk/busybox/ubirsvol
/debug_ramdisk/.magisk/busybox/ubirmvol
/debug_ramdisk/.magisk/busybox/ubirename
/debug_ramdisk/.magisk/busybox/ubimkvol
/debug_ramdisk/.magisk/busybox/ubidetach
/debug_ramdisk/.magisk/busybox/ubiattach
/debug_ramdisk/.magisk/busybox/tune2fs
/debug_ramdisk/.magisk/busybox/tunctl
/debug_ramdisk/.magisk/busybox/ttysize
/debug_ramdisk/.magisk/busybox/tty
/debug_ramdisk/.magisk/busybox/tsort
/debug_ramdisk/.magisk/busybox/ts
/debug_ramdisk/.magisk/busybox/truncate
/debug_ramdisk/.magisk/busybox/true
/debug_ramdisk/.magisk/busybox/tree
/debug_ramdisk/.magisk/busybox/traceroute6
/debug_ramdisk/.magisk/busybox/traceroute
/debug_ramdisk/.magisk/busybox/tr
/debug_ramdisk/.magisk/busybox/touch
/debug_ramdisk/.magisk/busybox/top
/debug_ramdisk/.magisk/busybox/timeout
/debug_ramdisk/.magisk/busybox/time
/debug_ramdisk/.magisk/busybox/tftpd
/debug_ramdisk/.magisk/busybox/tftp
/debug_ramdisk/.magisk/busybox/test
/debug_ramdisk/.magisk/busybox/telnetd
/debug_ramdisk/.magisk/busybox/telnet
/debug_ramdisk/.magisk/busybox/tee
/debug_ramdisk/.magisk/busybox/tcpsvd
/debug_ramdisk/.magisk/busybox/tc
/debug_ramdisk/.magisk/busybox/tar
/debug_ramdisk/.magisk/busybox/tail
/debug_ramdisk/.magisk/busybox/tac
/debug_ramdisk/.magisk/busybox/syslogd
/debug_ramdisk/.magisk/busybox/sysctl
/debug_ramdisk/.magisk/busybox/sync
/debug_ramdisk/.magisk/busybox/switch_root
/debug_ramdisk/.magisk/busybox/swapon
/debug_ramdisk/.magisk/busybox/swapoff
/debug_ramdisk/.magisk/busybox/svok
/debug_ramdisk/.magisk/busybox/svc
/debug_ramdisk/.magisk/busybox/sum
/debug_ramdisk/.magisk/busybox/stty
/debug_ramdisk/.magisk/busybox/strings
/debug_ramdisk/.magisk/busybox/stat
/debug_ramdisk/.magisk/busybox/start-stop-daemon
/debug_ramdisk/.magisk/busybox/ssl_client
/debug_ramdisk/.magisk/busybox/split
/debug_ramdisk/.magisk/busybox/sort
/debug_ramdisk/.magisk/busybox/smemcap
/debug_ramdisk/.magisk/busybox/sleep
/debug_ramdisk/.magisk/busybox/slattach
/debug_ramdisk/.magisk/busybox/shuf
/debug_ramdisk/.magisk/busybox/shred
/debug_ramdisk/.magisk/busybox/showkey
/debug_ramdisk/.magisk/busybox/sha512sum
/debug_ramdisk/.magisk/busybox/sha3sum
/debug_ramdisk/.magisk/busybox/sha256sum
/debug_ramdisk/.magisk/busybox/sha1sum
/debug_ramdisk/.magisk/busybox/sh
/debug_ramdisk/.magisk/busybox/setuidgid
/debug_ramdisk/.magisk/busybox/setsid
/debug_ramdisk/.magisk/busybox/setserial
/debug_ramdisk/.magisk/busybox/setpriv
/debug_ramdisk/.magisk/busybox/setlogcons
/debug_ramdisk/.magisk/busybox/setkeycodes
/debug_ramdisk/.magisk/busybox/setfont
/debug_ramdisk/.magisk/busybox/setfattr
/debug_ramdisk/.magisk/busybox/setenforce
/debug_ramdisk/.magisk/busybox/setconsole
/debug_ramdisk/.magisk/busybox/sestatus
/debug_ramdisk/.magisk/busybox/seq
/debug_ramdisk/.magisk/busybox/sendmail
/debug_ramdisk/.magisk/busybox/selinuxenabled
/debug_ramdisk/.magisk/busybox/seedrng
/debug_ramdisk/.magisk/busybox/sed
/debug_ramdisk/.magisk/busybox/scriptreplay
/debug_ramdisk/.magisk/busybox/script
/debug_ramdisk/.magisk/busybox/rx
/debug_ramdisk/.magisk/busybox/runcon
/debug_ramdisk/.magisk/busybox/run-parts
/debug_ramdisk/.magisk/busybox/run-init
/debug_ramdisk/.magisk/busybox/rtcwake
/debug_ramdisk/.magisk/busybox/route
/debug_ramdisk/.magisk/busybox/rmmod
/debug_ramdisk/.magisk/busybox/rmdir
/debug_ramdisk/.magisk/busybox/rm
/debug_ramdisk/.magisk/busybox/rfkill
/debug_ramdisk/.magisk/busybox/rev
/debug_ramdisk/.magisk/busybox/resume
/debug_ramdisk/.magisk/busybox/resize
/debug_ramdisk/.magisk/busybox/reset
/debug_ramdisk/.magisk/busybox/renice
/debug_ramdisk/.magisk/busybox/reformime
/debug_ramdisk/.magisk/busybox/reboot
/debug_ramdisk/.magisk/busybox/realpath
/debug_ramdisk/.magisk/busybox/readprofile
/debug_ramdisk/.magisk/busybox/readlink
/debug_ramdisk/.magisk/busybox/rdev
/debug_ramdisk/.magisk/busybox/rdate
/debug_ramdisk/.magisk/busybox/raidautorun
/debug_ramdisk/.magisk/busybox/pwdx
/debug_ramdisk/.magisk/busybox/pwd
/debug_ramdisk/.magisk/busybox/pstree
/debug_ramdisk/.magisk/busybox/pscan
/debug_ramdisk/.magisk/busybox/ps
/debug_ramdisk/.magisk/busybox/printf
/debug_ramdisk/.magisk/busybox/printenv
/debug_ramdisk/.magisk/busybox/powertop
/debug_ramdisk/.magisk/busybox/poweroff
/debug_ramdisk/.magisk/busybox/popmaildir
/debug_ramdisk/.magisk/busybox/pmap
/debug_ramdisk/.magisk/busybox/pkill
/debug_ramdisk/.magisk/busybox/pivot_root
/debug_ramdisk/.magisk/busybox/pipe_progress
/debug_ramdisk/.magisk/busybox/ping6
/debug_ramdisk/.magisk/busybox/ping
/debug_ramdisk/.magisk/busybox/pidof
/debug_ramdisk/.magisk/busybox/pgrep
/debug_ramdisk/.magisk/busybox/patch
/debug_ramdisk/.magisk/busybox/paste
/debug_ramdisk/.magisk/busybox/partprobe
/debug_ramdisk/.magisk/busybox/openvt
/debug_ramdisk/.magisk/busybox/od
/debug_ramdisk/.magisk/busybox/nuke
/debug_ramdisk/.magisk/busybox/nslookup
/debug_ramdisk/.magisk/busybox/nsenter
/debug_ramdisk/.magisk/busybox/nologin
/debug_ramdisk/.magisk/busybox/nohup
/debug_ramdisk/.magisk/busybox/nmeter
/debug_ramdisk/.magisk/busybox/nl
/debug_ramdisk/.magisk/busybox/nice
/debug_ramdisk/.magisk/busybox/netstat
/debug_ramdisk/.magisk/busybox/nc
/debug_ramdisk/.magisk/busybox/nbd-client
/debug_ramdisk/.magisk/busybox/nandwrite
/debug_ramdisk/.magisk/busybox/nanddump
/debug_ramdisk/.magisk/busybox/nameif
/debug_ramdisk/.magisk/busybox/mv
/debug_ramdisk/.magisk/busybox/mpstat
/debug_ramdisk/.magisk/busybox/mountpoint
/debug_ramdisk/.magisk/busybox/mount
/debug_ramdisk/.magisk/busybox/more
/debug_ramdisk/.magisk/busybox/modprobe
/debug_ramdisk/.magisk/busybox/modinfo
/debug_ramdisk/.magisk/busybox/mktemp
/debug_ramdisk/.magisk/busybox/mkswap
/debug_ramdisk/.magisk/busybox/mknod
/debug_ramdisk/.magisk/busybox/mkfs.vfat
/debug_ramdisk/.magisk/busybox/mkfs.reiser
/debug_ramdisk/.magisk/busybox/mkfs.minix
/debug_ramdisk/.magisk/busybox/mkfs.ext2
/debug_ramdisk/.magisk/busybox/mkfifo
/debug_ramdisk/.magisk/busybox/mke2fs
/debug_ramdisk/.magisk/busybox/mkdosfs
/debug_ramdisk/.magisk/busybox/mkdir
/debug_ramdisk/.magisk/busybox/mim
/debug_ramdisk/.magisk/busybox/microcom
/debug_ramdisk/.magisk/busybox/mesg
/debug_ramdisk/.magisk/busybox/md5sum
/debug_ramdisk/.magisk/busybox/man
/debug_ramdisk/.magisk/busybox/makemime
/debug_ramdisk/.magisk/busybox/makedevs
/debug_ramdisk/.magisk/busybox/lzopcat
/debug_ramdisk/.magisk/busybox/lzop
/debug_ramdisk/.magisk/busybox/lzma
/debug_ramdisk/.magisk/busybox/lzcat
/debug_ramdisk/.magisk/busybox/lsusb
/debug_ramdisk/.magisk/busybox/lsscsi
/debug_ramdisk/.magisk/busybox/lspci
/debug_ramdisk/.magisk/busybox/lsof
/debug_ramdisk/.magisk/busybox/lsmod
/debug_ramdisk/.magisk/busybox/lsattr
/debug_ramdisk/.magisk/busybox/ls
/debug_ramdisk/.magisk/busybox/losetup
/debug_ramdisk/.magisk/busybox/logread
/debug_ramdisk/.magisk/busybox/loadkmap
/debug_ramdisk/.magisk/busybox/loadfont
/debug_ramdisk/.magisk/busybox/ln
/debug_ramdisk/.magisk/busybox/link
/debug_ramdisk/.magisk/busybox/less
/debug_ramdisk/.magisk/busybox/klogd
/debug_ramdisk/.magisk/busybox/killall5
/debug_ramdisk/.magisk/busybox/killall
/debug_ramdisk/.magisk/busybox/kill
/debug_ramdisk/.magisk/busybox/kbd_mode
/debug_ramdisk/.magisk/busybox/iptunnel
/debug_ramdisk/.magisk/busybox/iprule
/debug_ramdisk/.magisk/busybox/iproute
/debug_ramdisk/.magisk/busybox/ipneigh
/debug_ramdisk/.magisk/busybox/iplink
/debug_ramdisk/.magisk/busybox/ipcs
/debug_ramdisk/.magisk/busybox/ipcrm
/debug_ramdisk/.magisk/busybox/ipcalc
/debug_ramdisk/.magisk/busybox/ipaddr
/debug_ramdisk/.magisk/busybox/ip
/debug_ramdisk/.magisk/busybox/iostat
/debug_ramdisk/.magisk/busybox/ionice
/debug_ramdisk/.magisk/busybox/install
/debug_ramdisk/.magisk/busybox/insmod
/debug_ramdisk/.magisk/busybox/inotifyd
/debug_ramdisk/.magisk/busybox/inetd
/debug_ramdisk/.magisk/busybox/ifup
/debug_ramdisk/.magisk/busybox/ifplugd
/debug_ramdisk/.magisk/busybox/ifenslave
/debug_ramdisk/.magisk/busybox/ifdown
/debug_ramdisk/.magisk/busybox/ifconfig
/debug_ramdisk/.magisk/busybox/id
/debug_ramdisk/.magisk/busybox/hwclock
/debug_ramdisk/.magisk/busybox/hush
/debug_ramdisk/.magisk/busybox/httpd
/debug_ramdisk/.magisk/busybox/hostname
/debug_ramdisk/.magisk/busybox/hexedit
/debug_ramdisk/.magisk/busybox/hexdump
/debug_ramdisk/.magisk/busybox/head
/debug_ramdisk/.magisk/busybox/hdparm
/debug_ramdisk/.magisk/busybox/hd
/debug_ramdisk/.magisk/busybox/gzip
/debug_ramdisk/.magisk/busybox/gunzip
/debug_ramdisk/.magisk/busybox/groups
/debug_ramdisk/.magisk/busybox/grep
/debug_ramdisk/.magisk/busybox/getopt
/debug_ramdisk/.magisk/busybox/getenforce
/debug_ramdisk/.magisk/busybox/fuser
/debug_ramdisk/.magisk/busybox/ftpput
/debug_ramdisk/.magisk/busybox/ftpget
/debug_ramdisk/.magisk/busybox/ftpd
/debug_ramdisk/.magisk/busybox/fsync
/debug_ramdisk/.magisk/busybox/fstrim
/debug_ramdisk/.magisk/busybox/fsfreeze
/debug_ramdisk/.magisk/busybox/fsck.minix
/debug_ramdisk/.magisk/busybox/fsck
/debug_ramdisk/.magisk/busybox/freeramdisk
/debug_ramdisk/.magisk/busybox/free
/debug_ramdisk/.magisk/busybox/fold
/debug_ramdisk/.magisk/busybox/flock
/debug_ramdisk/.magisk/busybox/flash_unlock
/debug_ramdisk/.magisk/busybox/flash_lock
/debug_ramdisk/.magisk/busybox/flash_eraseall
/debug_ramdisk/.magisk/busybox/findfs
/debug_ramdisk/.magisk/busybox/find
/debug_ramdisk/.magisk/busybox/fgrep
/debug_ramdisk/.magisk/busybox/fgconsole
/debug_ramdisk/.magisk/busybox/fdisk
/debug_ramdisk/.magisk/busybox/fdformat
/debug_ramdisk/.magisk/busybox/fdflush
/debug_ramdisk/.magisk/busybox/fbsplash
/debug_ramdisk/.magisk/busybox/fbset
/debug_ramdisk/.magisk/busybox/fatattr
/debug_ramdisk/.magisk/busybox/false
/debug_ramdisk/.magisk/busybox/fakeidentd
/debug_ramdisk/.magisk/busybox/factor
/debug_ramdisk/.magisk/busybox/expr
/debug_ramdisk/.magisk/busybox/expand
/debug_ramdisk/.magisk/busybox/ether-wake
/debug_ramdisk/.magisk/busybox/env
/debug_ramdisk/.magisk/busybox/eject
/debug_ramdisk/.magisk/busybox/egrep
/debug_ramdisk/.magisk/busybox/ed
/debug_ramdisk/.magisk/busybox/echo
/debug_ramdisk/.magisk/busybox/dumpleases
/debug_ramdisk/.magisk/busybox/dumpkmap
/debug_ramdisk/.magisk/busybox/du
/debug_ramdisk/.magisk/busybox/dos2unix
/debug_ramdisk/.magisk/busybox/dnsdomainname
/debug_ramdisk/.magisk/busybox/dnsd
/debug_ramdisk/.magisk/busybox/dmesg
/debug_ramdisk/.magisk/busybox/dirname
/debug_ramdisk/.magisk/busybox/diff
/debug_ramdisk/.magisk/busybox/dhcprelay
/debug_ramdisk/.magisk/busybox/df
/debug_ramdisk/.magisk/busybox/devmem
/debug_ramdisk/.magisk/busybox/depmod
/debug_ramdisk/.magisk/busybox/deallocvt
/debug_ramdisk/.magisk/busybox/dd
/debug_ramdisk/.magisk/busybox/dc
/debug_ramdisk/.magisk/busybox/date
/debug_ramdisk/.magisk/busybox/cut
/debug_ramdisk/.magisk/busybox/cttyhack
/debug_ramdisk/.magisk/busybox/crontab
/debug_ramdisk/.magisk/busybox/crond
/debug_ramdisk/.magisk/busybox/crc32
/debug_ramdisk/.magisk/busybox/cpio
/debug_ramdisk/.magisk/busybox/cp
/debug_ramdisk/.magisk/busybox/conspy
/debug_ramdisk/.magisk/busybox/comm
/debug_ramdisk/.magisk/busybox/cmp
/debug_ramdisk/.magisk/busybox/clear
/debug_ramdisk/.magisk/busybox/cksum
/debug_ramdisk/.magisk/busybox/chvt
/debug_ramdisk/.magisk/busybox/chrt
/debug_ramdisk/.magisk/busybox/chroot
/debug_ramdisk/.magisk/busybox/chown
/debug_ramdisk/.magisk/busybox/chmod
/debug_ramdisk/.magisk/busybox/chgrp
/debug_ramdisk/.magisk/busybox/chcon
/debug_ramdisk/.magisk/busybox/chattr
/debug_ramdisk/.magisk/busybox/chat
/debug_ramdisk/.magisk/busybox/cat
/debug_ramdisk/.magisk/busybox/cal
/debug_ramdisk/.magisk/busybox/bzip2
/debug_ramdisk/.magisk/busybox/bzcat
/debug_ramdisk/.magisk/busybox/bunzip2
/debug_ramdisk/.magisk/busybox/brctl
/debug_ramdisk/.magisk/busybox/blockdev
/debug_ramdisk/.magisk/busybox/blkid
/debug_ramdisk/.magisk/busybox/blkdiscard
/debug_ramdisk/.magisk/busybox/beep
/debug_ramdisk/.magisk/busybox/bbconfig
/debug_ramdisk/.magisk/busybox/basename
/debug_ramdisk/.magisk/busybox/base64
/debug_ramdisk/.magisk/busybox/base32
/debug_ramdisk/.magisk/busybox/awk
/debug_ramdisk/.magisk/busybox/ash
/debug_ramdisk/.magisk/busybox/ascii
/debug_ramdisk/.magisk/busybox/arping
/debug_ramdisk/.magisk/busybox/arp
/debug_ramdisk/.magisk/busybox/arch
/debug_ramdisk/.magisk/busybox/ar
/debug_ramdisk/.magisk/busybox/adjtimex
/debug_ramdisk/.magisk/busybox/acpid
/debug_ramdisk/.magisk/busybox/[[
/debug_ramdisk/.magisk/busybox/[
/debug_ramdisk/.magisk/busybox/busybox
/debug_ramdisk/.magisk/worker
/debug_ramdisk/.magisk/modules
/debug_ramdisk/.magisk/socket
/debug_ramdisk/.magisk/pts
/debug_ramdisk/.magisk/selinux
/debug_ramdisk/.magisk/selinux/enforce
/debug_ramdisk/.magisk/selinux/load
/debug_ramdisk/.magisk/rootdir
/debug_ramdisk/.magisk/rootdir/.mount_list
/debug_ramdisk/.magisk/rootdir/system
/debug_ramdisk/.magisk/rootdir/system/etc
/debug_ramdisk/.magisk/rootdir/system/etc/init
/debug_ramdisk/.magisk/rootdir/system/etc/init/hw
/debug_ramdisk/.magisk/rootdir/system/etc/init/hw/init.zygote64_32.rc
/debug_ramdisk/.magisk/rootdir/system/etc/init/hw/init.zygote32.rc
/debug_ramdisk/.magisk/rootdir/system/etc/init/hw/init.rc
/debug_ramdisk/.magisk/rootdir/sbin
/debug_ramdisk/.magisk/config
/debug_ramdisk/.magisk/preinit
/debug_ramdisk/.magisk/block
/debug_ramdisk/.magisk/block/preinit
/debug_ramdisk/.magisk/mirror
/debug_ramdisk/.magisk/mirror/preinit
/debug_ramdisk/magiskinit

**Comment by mywalkb** [comment]
Which Magisk Alpha are using? Your version don't install modules in standard path, /debug_ramdisk/.magisk/modules is empty. If I understand where modules are installed, I can support also this customization.

**Comment by mywalkb** [comment]
magisk alpha install module in old path /data/adb/modules, ok I develop a better search of dexpath

**Comment by mywalkb** [comment]
Test [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/6720288380) action when the build finish and let me to know if your issue persist

**Comment by u2shana** [comment]
Thanks.It work.
