### ISSUE TITLE
[BUGS] Cannot disable option "Enable watchdog logs"

### ISSUE THREAD

**Issue by nakcont** [mywalkb/LSPosed_mod#24]
### Steps to reproduce/复现步骤

Hi, i cannot disable option watchdog logs, when re-open lsposed , option active again. Please help me.
I think some applications crash with this option.
Thank you.

### Expected behaviour/预期行为

Crash

### Actual behaviour/实际行为

Crash

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

LSPosed-v1.9.2_mod-7184-zygisk-release

### Android version/Android 版本

13

### Magisk version/Magisk 版本

KSU 070

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by mywalkb** [comment]
The default behaviour as original LSPosed is the enabled option.
You can disable for test. [Here](https://github.com/mywalkb/LSPosed_mod/discussions/19#discussioncomment-7131969) I asked some test, but I never received a reply, so I think I will revert the patch.
Without logs I can't understand what happens.
You can test [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/6511831522) action, if you have the same behaviour: crash, that option is not the cause.

**Comment by mywalkb** [comment]
When [this action](https://github.com/mywalkb/LSPosed_mod/actions/runs/6762100042) finishes, you can test the fix.
Now the logic is correct, but if you disable the watchdog and the app continue to crash, there is no solution.
It was just a test. Try also to reboot. Sorry but I have no way to prove it. I don't have any apps with crash.
That's why I need feedback.

**Comment by nakcont** [comment]
Hi mywalkb, i tried with version 7185 and disable "Enable watchdog logs", but the app still crashes. LSPOSED origin same this problem. I'm try remove all hook still crash.
App test https://play.google.com/store/apps/details?id=id.bmri.livin
When i tried disable package id.bmri.livin in modules, app working. 
Thank you.
I tried

**Comment by mywalkb** [comment]
Unfortunately there are apps that can detect lsposed and there is no common way to protect yourself.
I bypassed detect magisk with my module DenyUnmount, but LSPosed is still detected.
I'll try to look at it to see if there is a solution.
