### ISSUE TITLE
Unable to install via VPhoneGaGa

### ISSUE THREAD

**Issue by QINYUUi** [mywalkb/LSPosed_mod#25]
### Steps to reproduce/复现步骤

Please check screenshot details

### Expected behaviour/预期行为

Install correctly

### Actual behaviour/实际行为

cannot be installed
![Screenshot_20231126_115733_com vphonegaga titan](https://github.com/mywalkb/LSPosed_mod/assets/151892850/dd19e92b-dfdc-4aca-9d0d-65ecefbbedfd)

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

7174

### Android version/Android 版本

9/10(Automatically virtualized by the emulator)

### Magisk version/Magisk 版本

26401

### Riru version/Riru 版本

Zygisk

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by mywalkb** [comment]
Duplicate #22 please read [this](https://github.com/mywalkb/LSPosed_mod/issues/22#issuecomment-1762024903) for resolve your issue

**Comment by QINYUUi** [comment]
> Duplicate #22 please read [this](https://github.com/mywalkb/LSPosed_mod/issues/22#issuecomment-1762024903) for resolve your issue

Wow! Now it installs and works fine, thanks sir for your help and guidance
![com vphonegaga titan](https://github.com/mywalkb/LSPosed_mod/assets/151892850/b45ca011-6bcf-4ca2-920c-a3e938542952)
