### ISSUE TITLE
Force stopping

### ISSUE THREAD

**Issue by e9239** [mywalkb/LSPosed_mod#26]
### Steps to reproduce/复现步骤

Opening LSPosed from the notification menu, stopped. Please check pastebin log.

### Expected behaviour/预期行为

  Crash

### Actual behaviour/实际行为

Crash

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

1.9.2

### Android version/Android 版本

12

### Magisk version/Magisk 版本

26.4

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

https://paste.ec/raw/FlCwDInx#LjPekK4fD3keHRXox88kKacT-GIGIAVopz2l246JaGZ

**Comment by mywalkb** [comment]
Have you tried installing the original lsposed?
In your log all init of LSPosed is missing, it's not very useful.

**Comment by e9239** [comment]
yes, tested original lsposed same issue ~ init log 

https://paste.ec/raw/+5Go8ntX#I6sxXU3YhPl+wZzxqf7SGsKSwK8mRY1gApq9C+llx-Z

**Comment by mywalkb** [comment]
I suggest to temporary switch original LSPosed so you can open an issue in that repository and got a better support than me. 
I only developed a small part of the project, so I can help you very well.
When the issue will be closed in that repository will be fixed also in this mod.

Before to switch, I suggestion to try uninstall and reinstall. The database sqlite is not correctly configured:
`E/SQLiteLog       ] (1) no such table: configs `

I see also these 2 problem:

```
[ 2023-12-17T18:35:20.260        0:   783:   783 W/LSPosedDex2Oat  ] Check mount failed for /apex/com.android.art/bin/dex2oat32
[ 2023-12-17T18:35:20.273        0:  1158:  1158 I/LSPosed         ] Enable dex2oat wrapper
[ 2023-12-17T18:35:20.300        0:   783:  1162 I/LSPosedDex2Oat  ] Dex2oat wrapper daemon start
[ 2023-12-17T18:35:20.302        0:   783:   783 E/SELinux         ] avc:  denied  { execute } for  scontext=u:r:untrusted_app:s0 tcontext=u:object_r:dex2oat_exec:s0 tclass=file permissive=0
[ 2023-12-17T18:35:20.303        0:   783:   783 E/SELinux         ] avc:  denied  { execute_no_trans } for  scontext=u:r:untrusted_app:s0 tcontext=u:object_r:dex2oat_exec:s0 tclass=file permissive=0
```
Some selinux permission is wrong.

**Comment by e9239** [comment]
thanks ~ do you have selinux rule or suggestions to test it?

**Comment by e9239** [comment]
thanks ~ do you have selinux rule or suggestions to test it?

**Comment by e9239** [comment]
do you have selinux rule or suggestions to test it?

**Comment by e9239** [comment]
thanks ~ do you have selinux rule or suggestions to test it?

**Comment by mywalkb** [comment]
try to replace this file [sepolice.rule.gz](https://github.com/mywalkb/LSPosed_mod/files/13697313/sepolice.rule.gz) (uncompress before upload) in /data/adb/modules/zygisk_lsposed/sepolicy.rule and reboot.
This add this rule:

`allow untrusted_app dex2oat_exec file {execute execute_no_trans}`

If this operation if not easy for you, I can generate a new zip with that rule.

**Comment by mywalkb** [comment]
I analyzed better the code and that rule cause dex2oat to doesn't work correctly.

**Comment by e9239** [comment]
how shall I proceed? thanks ~

**Comment by mywalkb** [comment]
- Have you tried uninstalling and reinstalling? Do you still have a SQLite error?
- After this test you can replace sepolicy.rule and reboot.
- If you still have an error you should switch to the original LSPosed, capture the log and open an issue on the original repository.

**Comment by e9239** [comment]
Same error as reported in the all logs ~ version 1.9.2 (7049) + sepolicy.rule. 

Closing, as there seems nothing we can do against it.
