### ISSUE TITLE
7228开始不能开启关闭模块

### ISSUE THREAD

**Issue by 0only** [mywalkb/LSPosed_mod#33]
### Steps to reproduce/复现步骤

1,更新7228,7229mod 的lsp
2,重启后lsp管理不能开关模块
管理器->模块->任何一个模块->启用模块->开关都无效
勾选推荐->提示Xposed模块未激活

### Expected behaviour/预期行为

模块无法开启

### Actual behaviour/实际行为

模块无法开启

### Xposed Module List/Xposed 模块列表

```shell
逗音小能手
```

### Magisk Module List/Magisk 模块列表

```shell
lsposed 1.92.7229
```

### LSPosed version/LSPosed 版本

7228,7229

### Android version/Android 版本

a10

### Magisk version/Magisk 版本

27.0

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2024-02-23T20_36_32.977.zip](https://github.com/mywalkb/LSPosed_mod/files/14385362/LSPosed_2024-02-23T20_36_32.977.zip)

**Comment by mywalkb** [comment]
Sorry I don't speak Chinese, I hope English is not a problem for you. 
I couldn't recreate your issue on an android 10 avd. Could you try [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8024130000) build?
The LSPlant update does not create any issues on Android 12 and 13, I have to check the other Android versions.

**Comment by 0only** [comment]
Thanks, I tried 7229 and still have the same problem.

1,Update the lsp of 7228,7229 mod.

2,after reboot lsp management can't switch modules on/off

Manager->Modules->Any module->Enable module->Switch does not work.

Check Recommended->Prompt Xposed module is not activated.

LSPosed-v1.9.2_mod-7229-zygisk-debug, please check the logs.

Thank you very much!

The 620 logs are from a reboot
[LSPosed_2024-02-24T06_24_12.483.zip](https://github.com/mywalkb/LSPosed_mod/files/14392609/LSPosed_2024-02-24T06_24_12.483.zip)
[LSPosed_2024-02-24T06_32_15.620.zip](https://github.com/mywalkb/LSPosed_mod/files/14392610/LSPosed_2024-02-24T06_32_15.620.zip)

**Comment by 0only** [comment]
Now using 1.92_mod 7221 everything works fine!

**Comment by 0only** [comment]
I just tried LSPosed-v1.9.2_mod-7230-zygisk-debug, same problem.
[LSPosed_2024-02-24T19_44_08.767.zip](https://github.com/mywalkb/LSPosed_mod/files/14392643/LSPosed_2024-02-24T19_44_08.767.zip)

**Comment by mywalkb** [comment]
> Now using 1.92_mod 7221 everything works fine!

Could you attach log for 7221? I'd like to see differences for understand better, between 7221 and 7228 there are updates dependency and external modules. 
I see strange errors in your log but they could be normal.
I need to find a way to replicate your issue to solve it better.

**Comment by 0only** [comment]
[LSPosed_2024-02-24T20_33_38.369.zip](https://github.com/mywalkb/LSPosed_mod/files/14392812/LSPosed_2024-02-24T20_33_38.369.zip)
Journal of 7221

**Comment by mywalkb** [comment]
Could you test [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8030881752) action? It should fix your issue.

**Comment by 0only** [comment]
7232,Thanks, it worked 

 

发件人: ***@***.*** ***@***.***> 代表 mywalkb
发送时间: 2024年2月24日 21:31
收件人: mywalkb/LSPosed_mod ***@***.***>
抄送: 0only ***@***.***>; Author ***@***.***>
主题: Re: [mywalkb/LSPosed_mod] 7228开始不能开启关闭模块 (Issue #33)

 

Could you test this <https://github.com/mywalkb/LSPosed_mod/actions/runs/8030881752>  action? It should fix your issue.
