### ISSUE TITLE
The github release file is broken

### ISSUE THREAD

**Issue by Evengard** [mywalkb/LSPosed_mod#44]
### Steps to reproduce/复现步骤

1. Download the latest release from github releases
2. Attempt to install
3. Observe error "cli is not found"

### Expected behaviour/预期行为

It should install correctly

### Actual behaviour/实际行为

Won't install, complains about it being corrupted, even though no actual corruption can be observed

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
XPosed
SUI
Universal SafetyNet Fix
```

### LSPosed version/LSPosed 版本

1.9.2_mod_7174_zygisk

### Android version/Android 版本

13

### Magisk version/Magisk 版本

Kitsune Mask R65C33E4F

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by lukemin** [comment]
same issue

**Comment by AllenChangMusic** [comment]
Can you guys try the newer builds and see if same issue? 
https://github.com/mywalkb/LSPosed_mod/actions/runs/8146230031

**Comment by AllenChangMusic** [comment]
For OP:
Why does your module list contain XPosed? You shouldn't need that if you are on Lsposed. Also, Universal Safetynet Fix doesn't work anymore, you should use PIF.

**Comment by mywalkb** [comment]
duplicate #22, please follow [this](https://github.com/mywalkb/LSPosed_mod/issues/22#issuecomment-1762024903) comment or use latest action in main branch.
I'll release asap a stable release

**Comment by Evengard** [comment]
@AllenChangMusic 
It was night and I made a mistake, sorry. It is of course lsposed.
