### ISSUE TITLE
[Info] Installation

### ISSUE THREAD

**Issue by B0j4ngl35** [mywalkb/LSPosed_mod#5]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Clarification of installation instructions.

### Describe the solution you'd like/描述你想要的解决方案

The installation instructions do not specify on whether or not it's advisable to install the modded version directly on top of the none modded version or is it mandatory to remove the non modded version before jumping on the bandwagon.

**Comment by mywalkb** [comment]
Rigth! You can install the modded version on top of previous official installation of LSPosed.
My mod add features. 
It's just add a field in database if doesn't exist.
