### ISSUE TITLE
LSPosed系统主题色问题

### ISSUE THREAD

**Issue by mJtUyT** [mywalkb/LSPosed_mod#64]
### Steps to reproduce/复现步骤

在LSPosed管理器设置中开启系统主题色

### Expected behaviour/预期行为

正常情况下管理器底栏的颜色应该与系统主题色接近或者相同

### Actual behaviour/实际行为

开启系统主题颜色以后，底栏的颜色为红色，并且无论当前主题是什么颜色，其底栏都为红色。滑动到下方后，顶部标题栏也会出现相同情况。手动调整颜色则不会出现。也许在原来的LSPosed CI版本就有的问题？
![Uploading Screenshot_2024-03-25-17-12-56-00_b7e9024f54bdc0532418cb6e23c85a7c.png…]()

### Xposed Module List/Xposed 模块列表

```shell
这与模块无关，即使没有安装模块也会有这种情况
```

### Magisk Module List/Magisk 模块列表

```shell
这与模块无关，即使没有安装模块也会有这种情况
```

### LSPosed version/LSPosed 版本

7244

### Android version/Android 版本

Android14

### Magisk version/Magisk 版本

KernelSU 0..9.2 11682

### Riru version/Riru 版本

zygisk

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[Uploading LSPosed_2024-03-25T17_13_20.692665.zip…]()

**Comment by mywalkb** [comment]
Sorry I don't speak Chinese, if for you is not a problem we can speak in english.
Could you re-upload the screenshot? The link is wrong, just for understand better your issue with colors.
Almost certainly the issue also existed on the original repository because I never modified the GUI graphics.
In original repository was @Howard20181 who very often deals with these graphics issues, if it want to contribute I will be happy to accept the PR, otherwise I'll try to solve it myself.

**Comment by Howard20181** [comment]
Removing dev.rikka.rikkax.material and then manually maintaining the color theme can fix this, or waiting for Rikka to update the library

**Comment by mJtUyT** [comment]
> 对不起，我不会说中文，如果对你来说不是问题，我们可以用英语说。你能重新上传屏幕截图吗？链接是错误的，只是为了更好地理解您的颜色问题。几乎可以肯定，原始存储库中也存在该问题，因为我从未修改过 GUI 图形。在原始存储库中，谁经常处理这些图形问题，如果它想做出贡献，我将很乐意接受 PR，否则我会尝试自己解决。

![Uploading Screenshot_2024-03-25-22-56-01-67_b7e9024f54bdc0532418cb6e23c85a7c.png…]()

**Comment by mJtUyT** [comment]
![Screenshot_2024-03-25-22-55-57-23_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/98fcad87-144d-4395-abac-ce9b202c42b8)

**Comment by mywalkb** [comment]
Could you give more details on this issue? 
I can't replicate the bottom bar red, also in your screenshot I can't see a red bar, maybe the translation is wrong and I don't understand your issue.
Have you tried to disable you xposed modules?

**Comment by xiaozhao45** [comment]
![Screenshot_20240331-170717_Lawnchair (Debug)](https://github.com/mywalkb/LSPosed_mod/assets/130202157/46a99099-91a1-44e9-8016-dee71e30df67)

As shown in the picture, one is LSPosed Manager, and the other is a program using Material Design 3.

However, LSPosed Manager has a color picking error.

But it works normally when "System theme color" is turned off.

This is not caused by Magisk modules and LSPosed modules.

Maybe this error exists in the official version of the LSPosed build manager app.

This passage is in Chinese, translated into English by ChatGPT. I'll be happy to explain any parts that are not clear.

Nevertheless, I hope this gets corrected.

**Comment by mywalkb** [comment]
Now I understand better, actually there was some small problem with the translation, I thought google translate had no problems.

**Comment by xiaozhao45** [comment]
Google translation services are not available in China (⁠〒⁠﹏⁠〒⁠),so I used ChatGPT。

When will this be resolved?My OCD(obsessive-compulsive disorder) is a little serious.(⁠;⁠;⁠;⁠・⁠_⁠・⁠)

**Comment by mywalkb** [comment]
> so I used ChatGPT

ChatGPT is good.

> When will this be resolved?

I don't have an ETA at the moment, in my mod I never modified the GUI except for small changes.
I confirm this issue exist also in original LSPosed, I tested with android 13 and 14, the same behaviour.

**Comment by xiaozhao45** [comment]
Fine,I'm not good at Android development, I may not be able to help you with this bug.This bug doesn't affect functionality.That is ok.

**Comment by mywalkb** [comment]
Could you test [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8498386613) when the build end?
I tested on avd, should fix your issue.

**Comment by mywalkb** [comment]
[Another](https://github.com/mywalkb/LSPosed_mod/actions/runs/8498496575) action, I forget to fix also fragment repo.

**Comment by mywalkb** [comment]
> I'm not good at Android development

It's ok, when this issue will be closed, if you want, you can translate with crowdin the new strings added by this mod.

**Comment by mywalkb** [comment]
I see your translations, but not the confirm if the [latest](https://github.com/mywalkb/LSPosed_mod/actions/runs/8498496575) action fix this issue. Is not urgent just for understand if you read previous messages.

**Comment by mJtUyT** [comment]
Although LSPosed has a color problem, it doesn't affect the main function. Manual adjustment works. I just hope I can fix this small error. Even if I can't fix it, I'm still happy to use LSPosed. Maybe the LSPosed team will come back one day to solve this problem?

**Comment by mJtUyT** [comment]
I installed the latest LSPosed _ mod-7266 and the color problem has been solved. Thank you very much for your hard work.

**Comment by mywalkb** [comment]
I added more changes to the commit, I tried to navigate all app and now should be totally fixed, if you have other situation where the colors are wrong just report it.
You can use the same 7266 (it is more updated than previous 7266).

**Comment by mJtUyT** [comment]
> 我在提交中添加了更多更改，我尝试浏览所有应用程序，现在应该完全修复，如果您有其他颜色错误的情况，请报告它。您可以使用相同的 7266（它比以前的 7266 更新更多）。

I have installed the updated 7266 and it has the following
![IMG_20240401_160536](https://github.com/mywalkb/LSPosed_mod/assets/132890073/996add9f-6033-47c6-aa4c-729604b6dda4)
I'm not sure if this is only happening on my device.

**Comment by mJtUyT** [comment]
There are also problems with the log interface.
As shown in the figure
![IMG_20240401_170944](https://github.com/mywalkb/LSPosed_mod/assets/132890073/48a7c560-d9da-4e57-a52c-ba761d7aae3c)

**Comment by mywalkb** [comment]
> I'm not sure if this is only happening on my device.

First and third screenshot, yes happeining only on your device and I can't replicate, but I'll try a solution also for this. 
Second screenshort I have the same issue.

**Comment by mywalkb** [comment]
> There are also problems with the log interface.

Also this problem I can't replicate, but I think is the same problem, so when will be resolved one all other will be.

**Comment by mJtUyT** [comment]
Switch background color

![IMG_20240401_172256](https://github.com/mywalkb/LSPosed_mod/assets/132890073/3e3cfdb0-bb0e-43c0-8e77-829a1574d4c5)

**Comment by mJtUyT** [comment]
> > 日志接口也存在问题。
> 
> 另外，这个问题我无法复制，但我认为是同一个问题，所以什么时候会解决一个所有其他


I installed the 7024 version of LSPosed, and unexpectedly found that the 7024 version of LSPosed has no color problem for the time being.At least not on my device.Maybe refer to the LSPosed of 7024.

![Screenshot_2024-04-01-17-34-20-53_b7e9024f54bdc0532418cb6e23c85a7c](https://
![Screenshot_2024-04-01-17-34-11-53_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/26abb0b7-0d56-4bfe-b169-ffc52a62d267)
![Screenshot_2024-04-01-17-34-07-96_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/9d13792d-19a9-4f3c-8650-fb7fa94d065d)
github.com/mywalkb/LSPosed_mod/assets/132890073/adf66a29-7ae8-4fcf-a2e1-bf6602d7536f)
![Screenshot_2024-04-01-17-34-16-77_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/4e1c00de-939e-45c5-b043-e6d2d45b610c)

**Comment by mywalkb** [comment]
> I installed the 7024 version of LSPosed, and unexpectedly found that the 7024 version of LSPosed has no color problem for the time being.At least not on my device.Maybe refer to the LSPosed of 7024.

Very strange, I tested the latest build on avd android 13 and 14 and there is the issue. I will try 7024.
Could you test [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8506479762) action, should solve all wrong color on tabs as Logs, Modules and Repositoty.

**Comment by mywalkb** [comment]
[These](https://github.com/LSPosed/LSPosed/compare/v1.9.2...master) are all commits between 7024 and latest. In these commits there is "Updates com.google.android.material:material from 1.10.0 to 1.11.0", most likely it was this update that inserted the bug.

**Comment by mywalkb** [comment]
With revert of update com.google.android.material the issues is solved. I will evaluate which is better revert or fix.

**Comment by mJtUyT** [comment]
> > 我安装了 7024 版本的 LSPosed，意外发现 7024 版本的 LSPosed 暂时没有颜色问题。至少不是在我的设备上。也许可以参考 7024 的 LSPosed。
> 
> 很奇怪，我在 avd android 13 和 14 上测试了最新版本，但存在问题。我会尝试 7024。您能否测试[此](https://github.com/mywalkb/LSPosed_mod/actions/runs/8506479762)操作，应该解决选项卡上的所有错误颜色，如日志、模块和存储库。

I have installed the 7267 version of LSPosed, and there is a problem with the module repository release interface and switch. The problems described elsewhere are now gone.

![IMG_20240401_175935](https://github.com/mywalkb/LSPosed_mod/assets/132890073/e82a97e9-c451-48e6-b7de-32181b539964)
![IMG_20240401_175950](https://github.com/mywalkb/LSPosed_mod/assets/132890073/5eb0dbe9-2a92-413e-b3c4-dfc863b312b3)

**Comment by mywalkb** [comment]
> The problems described elsewhere are now gone.

Good, that build resolve only that issue. 
I prefer to revert the com.google.android.material update, then in the future I will find a better solution.
I tested also 1.12.0-beta01 but no solution.

Could you try [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8506791076) action? It should solve definitively the issue.

**Comment by mJtUyT** [comment]
According to my tests, the color problem doesn't seem to be related to the manager, but I don't know where the problem is. 
I installed the 7024 version of LSPosed's Magisk module, and the manager continued to use the problematic 7266 version, with no color-related problems.
This is also only tested on my device

**Comment by mywalkb** [comment]
> I installed the 7024 version of LSPosed's Magisk module, and the manager continued to use the problematic 7266 version, with no color-related problems.

Try 7268, should solve the issue. On my avd all alertdialog has correct color.

**Comment by xiaozhao45** [comment]
I am sorry.My the reply was not timely enough because I needed to go to school.i will try new.

**Comment by mJtUyT** [comment]
> > 我安装了 LSPosed 的 Magisk 模块的 7024 版本，管理器继续使用有问题的 7266 版本，没有与颜色相关的问题。
> 
> 尝试 7268，应该可以解决问题。在我的 avd 上，所有警报对话框都有正确的颜色。

I have installed the 7268 Magisk module and manager, and the previously mentioned problems have been fixed, and no other color problems have been found. Thank you very much to the developer for fixing this problem.

**Comment by xiaozhao45** [comment]
Now that I have version 7268 installed, it's all right, and I'm thankful that a lot of open source software developers are here to take over when LSPosed officially doesn't have any news about the new version.thanks

**Comment by Activics** [comment]
Use this https://github.com/Mahmud0808/ColorBlendr/releases
it can fix it.
