### ISSUE TITLE
MOD THIS VERSION PLEASE 

### ISSUE THREAD

**Issue by QPLAYid** [mywalkb/LSPosed_mod#8]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

https://t.me/LSPosedDiscussion/1067959/1085245?single 

### Describe the solution you'd like/描述你想要的解决方案

Add select all apps

### Additional context/其他信息

Add select all apps

**Comment by mywalkb** [comment]
You can find all builds [here](https://github.com/mywalkb/LSPosed_mod/actions), for your version it's included [here](https://github.com/mywalkb/LSPosed_mod/actions/runs/3641377805)

**Comment by QPLAYid** [comment]
Thanks

Pada tanggal Sab, 14 Jan 2023 04.52, mywalkb ***@***.***>
menulis:
