### ISSUE TITLE
when enable LSPosed 1.9.3 Googleplay stop working

### ISSUE THREAD

**Issue by ionicArabic** [mywalkb/LSPosed_mod#82]
### Steps to reproduce

enable LSPosed on magisk module
reboot the phone
try to open Google Play but it not work. it stays on app logo screen forever 

### Expected behaviour

Googleplay run normally 

### Actual behaviour

Googleplay hang on logo screen forever 

### Xposed Module List

```shell
none enabled
```

### Magisk Module List

```shell
non enabled
```

### LSPosed version

1.9.3

### Android version

14

### Magisk version

27

### Riru version

N/A

### Version requirement

- [X] I am using latest debug CI version of LSPosed and enable verbose log

### Logs

[LSPosed_2024-04-26T14_41_42.198695.zip](https://github.com/mywalkb/LSPosed_mod/files/15130086/LSPosed_2024-04-26T14_41_42.198695.zip)

**Comment by mywalkb** [comment]
Configure in DenyList of Magisk Googleplay, if you don't want enforce the denylist you should use shamiko or my magisk module mywalkb/DenylistUnmount
