### ISSUE TITLE
notch screen rotation (landscape) icon showing

### ISSUE THREAD

**Issue by nusht** [mywalkb/LSPosed_mod#89]
### Steps to reproduce

notch screen rotation (landscape) icon showing 
when i rotate screen to landscape mode the punch hole of notch not get aways it's very disgusting please help me to fix this bug.

### Expected behaviour

when i rotate screen to landscape mode the punch hole of notch not get aways it's very disgusting please help me to fix this bug.

### Actual behaviour

when i rotate screen to landscape mode the punch hole of notch not get aways it's very disgusting please help me to fix this bug.

### Xposed Module List

```shell
lsposed mod
```

### Magisk Module List

```shell
lsposed
```

### LSPosed version

1.9.3 and old stock 1.9.2

### Android version

14

### Magisk version

27

### Riru version

N/A

### Version requirement

- [X] I am using latest debug CI version of LSPosed and enable verbose log

### Logs

when i rotate screen to landscape mode the punch hole of notch not get aways it's very disgusting please help me to fix this bug.

https://github.com/mywalkb/LSPosed_mod/assets/70893486/6cd04f55-8f5c-47c9-bd03-e5db246b0ed9

**Comment by mywalkb** [comment]
No logs, no device info. 
I can't reproduce your issue on avd or my real device with A14. Please give me more info.

**Comment by nusht** [comment]
redmi note 12 5g 
Android 14

[Uploading LSPosed_2024-05-05T22_22_54.525976.zip…]()

**Comment by mywalkb** [comment]
Wrong link of uploaded file, could you fix?
Android 14 is MIUI or a custom rom?

**Comment by nusht** [comment]
hyperos Android 14

**Comment by mywalkb** [comment]
Ok for hyperos, but now the link of logs is disappeared.
I don't have hyperos only a test device with MIUI a12.

**Comment by mywalkb** [comment]
I'll reopen the issue when you will attach debug log.
