### ISSUE TITLE
Update version canary please 

### ISSUE THREAD

**Issue by QPLAYid** [mywalkb/LSPosed_mod#9]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Canary version or daily update version

### Describe the solution you'd like/描述你想要的解决方案

Canary version or daily update version

### Additional context/其他信息

Canary version or daily update version

**Comment by mywalkb** [comment]
You can find [here](https://github.com/mywalkb/LSPosed_mod/actions/runs/4026823851)
